version: '3.9'

services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      target: symfony_php
    volumes:
      - ./:/srv/app:rw,cached
  db:
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_USER: ${DATABASE_USER}
        MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    cap_add:
      - SYS_NICE
