version: '3.9'

services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      target: symfony_php
    volumes:
      - ./:/srv/app:rw,cached    
  db:
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    cap_add:
      - SYS_NICE
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
