version: '3.9'

services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      target: symfony_php
    volumes:
      - ./:/srv/app
  db:
    build:
      context: ./
      dockerfile: docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
